contact_links:
  - name: Fabric Discord
    url: https://discord.gg/RyPwrj5TDk
    about: Please do not create issues regarding help with content on the wiki - you should ask in the '#mod-dev' channels on the Fabric Discord instead.
