name: Documentation Request
description: Request documentation to be added to the community wiki.
title: "Documentation - "
labels: ["Documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a guide request.
        Please ensure the topic in question can not be classed as a guide!
        Documentation exists as a reference on usage - not to teach.
  - type: textarea
    id: topic
    attributes:
      label: What do you want to see added?
      description: |
        Please describe the topic in question.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Tell us about the topic!
      value: "I would like to see documentation about..."
    validations:
      required: true
  - type: dropdown
    id: multitopic
    attributes:
      label: Would this topic span multiple pages?
      multiple: false
      options:
        - 'Yes'
        - 'No'
        - 'Not Sure'
    validations:
      required: true
